In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Wissen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Wissen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.3 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/9.8 MB 1.5 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/9.8 MB 1.6 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.8 MB 1.7 MB/s eta 0:00:05
   ---------- ----------------------------- 2.6/9.8 MB 2.0 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.8 MB 2.1 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 2.3 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.8 MB 2.7 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.8 MB 3.1 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.8 MB 3.3 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.8 MB 3.3 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.8 MB 3.3 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.8 MB 2.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 2.9 MB/s  0:00:03
Downloading numpy-2.4.6-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.3 MB 5.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.3 MB 4.3 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.3 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.3 MB 3.6 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.3 MB 4.0 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.3 MB 4.1 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.3 MB 4.1 MB/s eta 0:00:02
   ----------------- ---------------------- 5.2/12.3 MB 3.1 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.3 MB 3.2 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.3 MB 3.4 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.3 MB 3.5 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.3 MB 3.3 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.3 MB 3.3 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 3.4 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 3.2 MB/s  0:00:03
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.6 pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\Wissen\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.3'

In [5]:
# 1. Create Dataframe
df = pd.DataFrame([1,2,3],columns=['Col_Name'])
print(df)

   Col_Name
0         1
1         2
2         3

In [6]:
print(type(df))

<class 'pandas.DataFrame'>

In [7]:
data = {
    'Name' : ['Madhav','Akhil','Pranay','Nikhil'],
    'Age' : [16,17,18,19],
    'Salary' : [90000,50000,40000,60000]

}

In [9]:
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0  Madhav   16   90000
1   Akhil   17   50000
2  Pranay   18   40000
3  Nikhil   19   60000

In [10]:
# 2 Basic DataFrame Understanding

df.head(2)

     Name  Age  Salary
0  Madhav   16   90000
1   Akhil   17   50000

In [11]:
df.tail(2)

     Name  Age  Salary
2  Pranay   18   40000
3  Nikhil   19   60000

In [12]:
df.shape

(4, 3)

In [13]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [14]:
df.rename(columns={'Salary':'Monthly_Salary'})

     Name  Age  Monthly_Salary
0  Madhav   16           90000
1   Akhil   17           50000
2  Pranay   18           40000
3  Nikhil   19           60000

In [16]:
df # wont change the col name since not saved in variable .. u have to say inplace=True to make it permanent

     Name  Age  Salary
0  Madhav   16   90000
1   Akhil   17   50000
2  Pranay   18   40000
3  Nikhil   19   60000

In [17]:
df.rename(columns={'Salary':'Weekly_Salary'},inplace=True)

In [18]:
df

     Name  Age  Weekly_Salary
0  Madhav   16          90000
1   Akhil   17          50000
2  Pranay   18          40000
3  Nikhil   19          60000

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           4 non-null      str
 1   Age            4 non-null      int64
 2   Weekly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [21]:
df.describe()

             Age  Weekly_Salary
count   4.000000       4.000000
mean   17.500000   60000.000000
std     1.290994   21602.468995
min    16.000000   40000.000000
25%    16.750000   47500.000000
50%    17.500000   55000.000000
75%    18.250000   67500.000000
max    19.000000   90000.000000

In [22]:
# save and load data into csv

df.to_csv('Test_data.csv')

In [77]:
load_df = pd.read_csv('Test_data.csv')

In [78]:
load_df

   Unnamed: 0    Name  Age  Weekly_Salary
0           0  Madhav   16          90000
1           1   Akhil   17          50000
2           2  Pranay   18          40000
3           3  Nikhil   19          60000

In [79]:
# select column 

df[['Name','Weekly_Salary']]

KeyError: "None of [Index(['Name', 'Weekly_Salary'], dtype='str')] are in the [index]"

In [ ]:
#select rows
# loc - index name based
df.loc[df.Name=='Madhav']
df.loc[(df.Name=='Madhav') & (df.Weekly_Salary>=50000)]

     Name  Age  Weekly_Salary
0  Madhav   16          90000

In [ ]:
#iloc - index-value based
df.iloc[0]

Name             Madhav
Age                  16
Weekly_Salary     90000
Name: 0, dtype: object

In [ ]:
df.iloc[0:2] # slicing excludes 2

     Name  Age  Weekly_Salary
0  Madhav   16          90000
1   Akhil   17          50000

In [80]:
# filter dataframe 

df['Age'] > 18

KeyError: 'Age'

In [81]:
df_age_filter = df[df['Age'] >=18]
df_age_filter

KeyError: 'Age'

In [82]:
df[(df['Age'] >=18) & (df['Weekly_Salary'] >=50000)]

KeyError: 'Age'

In [83]:
df.where(df['Age'] >=18)

KeyError: 'Age'

In [84]:
df.where(df['Age'] >=18, other='Not Eligible')

KeyError: 'Age'

In [85]:
# Row and Columns - Operations (Add,Update,Delete)

df

0                                   2024-01-01 00:00:00
1                                   2024-01-15 00:00:00
2                                   2024-03-28 00:00:00
3                                   2024-03-03 00:00:00
DOJ    [2024-01-01, 2024-01-15, 2024-03-28, 2024-03-03]
Name: DOJ, dtype: object

In [86]:
# add new column 

df['Team'] = ['CEO','HR','CTO','DA']

In [87]:
df

0                                    2024-01-01 00:00:00
1                                    2024-01-15 00:00:00
2                                    2024-03-28 00:00:00
3                                    2024-03-03 00:00:00
DOJ     [2024-01-01, 2024-01-15, 2024-03-28, 2024-03-03]
Team                                  [CEO, HR, CTO, DA]
Name: DOJ, dtype: object

In [88]:
df['Bonus'] = df['Weekly_Salary']*0.2

KeyError: 'Weekly_Salary'

In [89]:
df

0                                    2024-01-01 00:00:00
1                                    2024-01-15 00:00:00
2                                    2024-03-28 00:00:00
3                                    2024-03-03 00:00:00
DOJ     [2024-01-01, 2024-01-15, 2024-03-28, 2024-03-03]
Team                                  [CEO, HR, CTO, DA]
Name: DOJ, dtype: object

In [47]:
# add new row 

df.loc[len(df)] = ['Abc',21,21000,'IT',4000]

In [48]:
df

     Name  Age  Weekly_Salary Team    Bonus
0  Madhav   16          90000  CEO  18000.0
1   Akhil   17          50000   HR  10000.0
2  Pranay   18          40000  CTO   8000.0
3  Nikhil   19          60000   DA  12000.0
4     Abc   21          21000   IT   4000.0

In [49]:
len(df)

5

In [ ]:
# update value - using index name

df.loc[0,'Weekly_Salary'] = 95000
df

     Name  Age  Weekly_Salary Team    Bonus
0  Madhav   16          95000  CEO  18000.0
1   Akhil   17          50000   HR  10000.0
2  Pranay   18          40000  CTO   8000.0
3  Nikhil   19          60000   DA  12000.0
4     Abc   21          21000   IT   4000.0

In [51]:
# update value - using column name 

df.loc[df.Name == 'Madhav','Weekly_Salary'] = 100000

In [52]:
df

     Name  Age  Weekly_Salary Team    Bonus
0  Madhav   16         100000  CEO  18000.0
1   Akhil   17          50000   HR  10000.0
2  Pranay   18          40000  CTO   8000.0
3  Nikhil   19          60000   DA  12000.0
4     Abc   21          21000   IT   4000.0

In [58]:
# delete value 

# df.drop() # axis = 0 (row) 1 (cols)
df = df.drop(df[df.Name=='Abc'].index) # drop row

In [59]:
df.drop('Bonus',axis=1,inplace=True)

In [60]:
df

     Name  Age  Weekly_Salary Team
0  Madhav   16         100000  CEO
1   Akhil   17          50000   HR
2  Pranay   18          40000  CTO
3  Nikhil   19          60000   DA

In [61]:
df.drop(1,axis=0) # index name

     Name  Age  Weekly_Salary Team
0  Madhav   16         100000  CEO
2  Pranay   18          40000  CTO
3  Nikhil   19          60000   DA

In [62]:
# sort value 

df.sort_values('Weekly_Salary')

     Name  Age  Weekly_Salary Team
2  Pranay   18          40000  CTO
1   Akhil   17          50000   HR
3  Nikhil   19          60000   DA
0  Madhav   16         100000  CEO

In [63]:

df.sort_values('Weekly_Salary',ascending=False)

     Name  Age  Weekly_Salary Team
0  Madhav   16         100000  CEO
3  Nikhil   19          60000   DA
1   Akhil   17          50000   HR
2  Pranay   18          40000  CTO

In [74]:
# working with Date values 

df['DOJ'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03']

In [76]:

df

0                                   2024-01-01 00:00:00
1                                   2024-01-15 00:00:00
2                                   2024-03-28 00:00:00
3                                   2024-03-03 00:00:00
DOJ    [2024-01-01, 2024-01-15, 2024-03-28, 2024-03-03]
Name: DOJ, dtype: object

In [72]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

KeyError: 'DOJ'

In [73]:
df['DOJ'].dtype

KeyError: 'DOJ'

In [92]:
df_1 = pd.read_csv('Test_data.csv')

In [97]:
df_1['DOJ'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03']

In [98]:
df_1

   Unnamed: 0    Name  Age  Weekly_Salary         DOJ
0           0  Madhav   16          90000  2024-01-01
1           1   Akhil   17          50000  2024-01-15
2           2  Pranay   18          40000  2024-03-28
3           3  Nikhil   19          60000  2024-03-03

In [101]:
df_1['DOJ'].dtype

In [102]:
df_1['DOJ'] = pd.to_datetime(df['DOJ'])

In [103]:
df_1

   Unnamed: 0    Name  Age  Weekly_Salary        DOJ
0           0  Madhav   16          90000 2024-01-01
1           1   Akhil   17          50000 2024-01-15
2           2  Pranay   18          40000 2024-03-28
3           3  Nikhil   19          60000 2024-03-03

In [104]:
df_1['DOJ'].dtype

dtype('<M8[us]')

In [106]:
df_1['DOJ2'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03']

In [107]:
df_1['DOJ2'].dtype

In [109]:
df_1['DOJ2'] = pd.to_datetime(df_1['DOJ2'],format='%Y-%m-%d')

In [110]:
df_1

   Unnamed: 0    Name  Age  Weekly_Salary        DOJ       DOJ2
0           0  Madhav   16          90000 2024-01-01 2024-01-01
1           1   Akhil   17          50000 2024-01-15 2024-01-15
2           2  Pranay   18          40000 2024-03-28 2024-03-28
3           3  Nikhil   19          60000 2024-03-03 2024-03-03

In [113]:
df_1['DOJ'].dt.year

0    2024
1    2024
2    2024
3    2024
Name: DOJ, dtype: int32

In [114]:
df_1['DOJ'].dt.month

0    1
1    1
2    3
3    3
Name: DOJ, dtype: int32

In [115]:
df_1['DOJ'].dt.day

0     1
1    15
2    28
3     3
Name: DOJ, dtype: int32

In [116]:
df_1['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: str

In [125]:
df_1['DOJ'] - pd.Timedelta(days=30)

0   2023-12-02
1   2023-12-16
2   2024-02-27
3   2024-02-02
Name: DOJ, dtype: datetime64[us]

In [126]:
df_1

   Unnamed: 0    Name  Age  Weekly_Salary        DOJ       DOJ2
0           0  Madhav   16          90000 2024-01-01 2024-01-01
1           1   Akhil   17          50000 2024-01-15 2024-01-15
2           2  Pranay   18          40000 2024-03-28 2024-03-28
3           3  Nikhil   19          60000 2024-03-03 2024-03-03

In [132]:
import numpy as np
df_1.loc[df_1.Name=='Nikhil','Salary'] =np.nan

In [133]:
df_1

   Unnamed: 0    Name  Age  Weekly_Salary        DOJ       DOJ2  Salary
0           0  Madhav   16          90000 2024-01-01 2024-01-01     NaN
1           1   Akhil   17          50000 2024-01-15 2024-01-15     NaN
2           2  Pranay   18          40000 2024-03-28 2024-03-28     NaN
3           3  Nikhil   19          60000 2024-03-03 2024-03-03     NaN

In [134]:
df_1.isnull()

   Unnamed: 0   Name    Age  Weekly_Salary    DOJ   DOJ2  Salary
0       False  False  False          False  False  False    True
1       False  False  False          False  False  False    True
2       False  False  False          False  False  False    True
3       False  False  False          False  False  False    True

In [136]:
df_1.isnull().sum()

Unnamed: 0       0
Name             0
Age              0
Weekly_Salary    0
DOJ              0
DOJ2             0
Salary           4
dtype: int64

In [137]:
df_1.fillna(0)

   Unnamed: 0    Name  Age  Weekly_Salary        DOJ       DOJ2  Salary
0           0  Madhav   16          90000 2024-01-01 2024-01-01     0.0
1           1   Akhil   17          50000 2024-01-15 2024-01-15     0.0
2           2  Pranay   18          40000 2024-03-28 2024-03-28     0.0
3           3  Nikhil   19          60000 2024-03-03 2024-03-03     0.0

In [138]:
df = pd.read_csv('Test_data.csv')

In [139]:
df

   Unnamed: 0    Name  Age  Weekly_Salary
0           0  Madhav   16          90000
1           1   Akhil   17          50000
2           2  Pranay   18          40000
3           3  Nikhil   19          60000

In [140]:
df['DOJ'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03']

In [141]:
df

   Unnamed: 0    Name  Age  Weekly_Salary         DOJ
0           0  Madhav   16          90000  2024-01-01
1           1   Akhil   17          50000  2024-01-15
2           2  Pranay   18          40000  2024-03-28
3           3  Nikhil   19          60000  2024-03-03

In [143]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [144]:
df

   Unnamed: 0    Name  Age  Weekly_Salary        DOJ
0           0  Madhav   16          90000 2024-01-01
1           1   Akhil   17          50000 2024-01-15
2           2  Pranay   18          40000 2024-03-28
3           3  Nikhil   19          60000 2024-03-03

In [146]:
df['Month'] = df['DOJ'].dt.month

In [147]:
df

   Unnamed: 0    Name  Age  Weekly_Salary        DOJ  Month
0           0  Madhav   16          90000 2024-01-01      1
1           1   Akhil   17          50000 2024-01-15      1
2           2  Pranay   18          40000 2024-03-28      3
3           3  Nikhil   19          60000 2024-03-03      3

In [149]:
df['Month'].value_counts() #freq of val

Month
1    2
3    2
Name: count, dtype: int64

In [151]:
df.groupby('Month')['Weekly_Salary'].sum()

Month
1    140000
3    100000
Name: Weekly_Salary, dtype: int64

In [152]:
df.groupby('Month')['Weekly_Salary'].mean()

Month
1    70000.0
3    50000.0
Name: Weekly_Salary, dtype: float64

In [154]:
df.groupby('Month').agg({'Weekly_Salary':'mean','Name':'count'})

       Weekly_Salary  Name
Month
1            70000.0     2
3            50000.0     2

In [155]:
# concatenate and merge dataframe (JOINS)

df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [156]:
# concatenate and merge dataframe (JOINS)

df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [ ]:
pd.concat([df1,df2],axis=0) # ek k neeche ek row

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [158]:
pd.concat([df1,df2],axis=1) # ek k neeche ek col

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [159]:
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [160]:
pd.merge(df1,df2,how='inner',left_on='ID',right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [162]:
df.query('Month == 1 and Weekly_Salary >=50000') #query method

   Unnamed: 0    Name  Age  Weekly_Salary        DOJ  Month
0           0  Madhav   16          90000 2024-01-01      1
1           1   Akhil   17          50000 2024-01-15      1